# docker-compose.yml - Composition of micro-services to run OpenDLV software.
# Copyright (C) 2016 Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2016-10-16

version: '2'

services:
    odsupercomponent:
        image: ${IMAGE}
        network_mode: host
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"

    odcockpit:
        image: ${IMAGE}
        network_mode: host
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - /media/weiming/46823A5A823A4F252/data/2018-07-26_170052:/opt/recordings
        ipc: host
        user: odv
        depends_on:
            - odsupercomponent
        command: "/opt/od4/bin/odcockpit --cid=${CID}" 

    cfsd18-perception-detectcone:
        image: "detectcone:test"
        # image: "chalmersfsd/cfsd18-perception-detectcone:master-f5b38b1"
        network_mode: "host"
        ipc: host
        working_dir: /opt
        environment:
          - DISPLAY=$DISPLAY
          - CLUON_SHAREDMEMORY_POSIX=1
        volumes:
         - /tmp/.X11-unix:/tmp/.X11-unix
         - /media/weiming/46823A5A823A4F252/data/2018-07-26_170052:/opt
         - /media/weiming/Ny volym/ubuntu-project/cone-detection/models/model:/opt/model
         - "/dev/shm:/dev/shm"
        # depends_on:
        #   - proxy-camera
        ulimits:
          memlock:
            soft: 5600000 #1516032
            hard: 5600000
        command: "cfsd18-perception-detectcone --cid=${CID} --name=cam0 --width=2560 --height=720 --bpp=24 --threshold=0.7 
        --timeDiffMilliseconds=40 --separationTimeMs=20 --checkLidarMilliseconds=1000 --senderStamp=118 --attentionSenderStamp=116 
        --offline=1 --annotate=0 --stateMachineId=1401 --readyStateMachine=1 --forwardDetection=0 --fastThreshold=3
        --matchDistance=1.5"

    # cfsd18-sensation-attention:
    #     image: "chalmersfsd/cfsd18-sensation-attention:pre-release-69baa73"
    #     network_mode: "host"
    #     ipc: host
    #     command: "cfsd18-sensation-attention --cid=${CID} --verbose --id=116 --xBoundary=4 --yBoundary=12 
    #     --zUpperBoundary=0.6 --groundClusterDistanceThreshold=0.3 --groundClusterSizeThreshold=60 
    #     --connectDistanceThreshold=0.15 --minNumOfPointsForCone=3 --maxNumOfPointsForCone=300 
    #     --coneRadiusThreshold=0.15 --zRangeThreshold=0.0 --inlierRangeThreshold=0.06 --dotThreshold=0.1 
    #     --inlierFoundThreshold=500 --numberOfIterations=30 --stateMachineId=1401 --readyStateMachine=1"


    # proxy-camera:
    #     image: producer:latest #cproxy:cproxyv1
    #     network_mode: host
    #     group_add:
    #         - video
    #     ipc: host
    #     devices:
    #         - "/dev/video0:/dev/video0"
    #     environment:
    #         - DISPLAY=$DISPLAY
    #     volumes:
    #         - /tmp/.X11-unix:/tmp/.X11-unix
    #         - "/dev/shm:/dev/shm"
    #     ulimits:
    #       memlock:
    #         soft: 5600000 #1516032
    #         hard: 5600000
    #     command: "opendlv-device-camera-opencv --name=cam0 --bgr2rgb --cid=118 --camera=/dev/video0 --width=640 --height=360 --bpp=24 --freq=60 --verbose"

    # cfsd18-perception-imagerecorder:
    #     image: "imgrec:imgrecv0"
    #     network_mode: "host"
    #     ipc: host
    #     volumes:
    #     - ../tmp:/opt
    #     depends_on:
    #       - proxy-camera
    #     command: "cfsd18-perception-imagerecorder --cid=${CID} --name=cam0 --width=640 --height=360 --bpp=24 --verbose --id=1"


   


